### ISSUE TITLE
Implement team user endpoints

### ISSUE THREAD

**Issue by Crevil** [lokalise/lokalise-go-sdk#12]
Documentation: https://lokalise.co/api2docs/go/#resource-team-users

**Endpoints**

- [x] List all team users (paginated)
- [x] Retrieve a team user
- [x] Update a team user
- [x] Delete a team user

**Comment by Crevil** [comment]
@nickustinov I've started implementing the client for this, but the documentation seems to have an unconsistency.

The example response for retrieving a team user states the team id as a string, but it's a number other places. I expect this to be a string?

https://lokalise.co/api2docs/curl/#transition-retrieve-a-team-user-get

**Comment by nickustinov** [comment]
@andrewi-wd Please check this. I assume it supposed to be int in all cases?

**Comment by andrewi-wd** [comment]
@Crevil Its a documentation mistake. Actual response has `team_id` as integer (number)
